{
    'name': 'AT- Odoo 18 Fiscal Year & Lock Date',
    'version': '1.0.1',
    'category': 'Accounting',
    'summary': 'Odoo 18 Fiscal Year, Fiscal Year in Odoo 18, Lock Date in Odoo 18',
    'description': 'Odoo 18 Fiscal Year, Fiscal Year in Odoo 18',
    'live_test_url': 'https://www.youtube.com/watch?v=Kj4hR7_uNs4',
    'sequence': '1',
    'website': 'https://wa.me/966553493285',
    'author': 'AccountTechs',
    'maintainer': 'AccountTechs',
    'license': 'LGPL-3',
    'support': 'osamahalnihmi@gmail.com',
    'depends': ['account'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'wizard/change_lock_date.xml',
        'views/fiscal_year.xml',
        'views/settings.xml',
    ],
    'images': ['static/description/banner.png'],
}
